# Generated by Django 2.2.6 on 2019-12-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDescr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date_become_client', models.DateTimeField(auto_now_add=True)),
                ('other_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_custom', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_custom', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('company_name', models.CharField(max_length=64, verbose_name='company_name')),
                ('identifier', models.CharField(max_length=32)),
                ('vat_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('table_name', models.CharField(max_length=64, unique=True)),
                ('hier_type', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=64, unique=True)),
                ('model_name', models.CharField(max_length=64, unique=True)),
                ('app_label', models.CharField(max_length=64)),
                ('table_descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bunch_Client',
            fields=[
                ('tablename', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eprectest.Trunk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bunch_Contact',
            fields=[
                ('tablename', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eprectest.Trunk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_custom', models.BooleanField(default=True)),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eprectest.EmailCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('born', models.DateField()),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.GenderCategory')),
            ],
        ),
        migrations.AddField(
            model_name='gendercategory',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.Translation'),
        ),
        migrations.CreateModel(
            name='EpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.Translation'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='eprectest.EmailCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_custom', models.BooleanField(default=True)),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='AddressCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_custom', models.BooleanField(default=True)),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eprectest.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_row_id', models.IntegerField(db_index=True)),
                ('index_as_child', models.IntegerField(db_index=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprectest.Contact')),
                ('bunch_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprectest.Bunch_Contact')),
            ],
            options={
                'abstract': False,
                'unique_together': {('index_as_child', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_row_id', models.IntegerField(db_index=True)),
                ('index_as_child', models.IntegerField(db_index=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprectest.Client')),
                ('bunch_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eprectest.Bunch_Client')),
            ],
            options={
                'abstract': False,
                'unique_together': {('index_as_child', 'parent')},
            },
        ),
    ]
