# Generated by Django 2.2.6 on 2019-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprectest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_without_unique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=20)),
                ('text2', models.CharField(max_length=20)),
            ],
        ),
    ]
