# Generated by Django 2.2.6 on 2019-12-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprectest', '0002_test_without_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_without_unique',
        ),
    ]
